### ISSUE TITLE
Can't open the docs

### ISSUE THREAD

**Issue by Sleedyak** [grokkers/cr-async#14]
when I click on the link with docs it gives me 404.

**Comment by fourjr** [comment]
which link?

**Comment by Sleedyak** [comment]
It works now, just the crasync docs didn't work it gave a 404.

**Comment by fourjr** [comment]
where's the link to the crasync docs that didn't work?

**Comment by Sleedyak** [comment]
For the entire docs..

**Comment by fourjr** [comment]
Think fixed in #2f27705
