### ISSUE TITLE
your docs lie (see images)

### ISSUE THREAD

**Issue by SharpBit** [grokkers/cr-async#9]
`1.` https://gyazo.com/b930836df33a0a90b2dda166b57a3f70
`2.` https://gyazo.com/2537bfe54d2104106e38e237d14b568d

**Comment by fourjr** [comment]
win_streak is currently in testing and will be on pypi soon. For the other one, get_chest, likely that your PC isn't updated.

**Comment by fourjr** [comment]
win streak is on pypi (should be)
